// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ArtemHvozdov/bestieverse.git/internal/domain/repository (interfaces: PlayerRepository)

package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/ArtemHvozdov/bestieverse.git/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

type MockPlayerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerRepositoryMockRecorder
}

type MockPlayerRepositoryMockRecorder struct {
	mock *MockPlayerRepository
}

func NewMockPlayerRepository(ctrl *gomock.Controller) *MockPlayerRepository {
	mock := &MockPlayerRepository{ctrl: ctrl}
	mock.recorder = &MockPlayerRepositoryMockRecorder{mock}
	return mock
}

func (m *MockPlayerRepository) EXPECT() *MockPlayerRepositoryMockRecorder {
	return m.recorder
}

func (m *MockPlayerRepository) Create(ctx context.Context, player *entity.Player) (*entity.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, player)
	ret0, _ := ret[0].(*entity.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockPlayerRepositoryMockRecorder) Create(ctx, player any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "Create", reflect.TypeOf((*MockPlayerRepository)(nil).Create), ctx, player)
}

func (m *MockPlayerRepository) GetByGameAndTelegramID(ctx context.Context, gameID uint64, telegramUserID int64) (*entity.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGameAndTelegramID", ctx, gameID, telegramUserID)
	ret0, _ := ret[0].(*entity.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockPlayerRepositoryMockRecorder) GetByGameAndTelegramID(ctx, gameID, telegramUserID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetByGameAndTelegramID", reflect.TypeOf((*MockPlayerRepository)(nil).GetByGameAndTelegramID), ctx, gameID, telegramUserID)
}

func (m *MockPlayerRepository) GetAllByGame(ctx context.Context, gameID uint64) ([]*entity.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByGame", ctx, gameID)
	ret0, _ := ret[0].([]*entity.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockPlayerRepositoryMockRecorder) GetAllByGame(ctx, gameID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetAllByGame", reflect.TypeOf((*MockPlayerRepository)(nil).GetAllByGame), ctx, gameID)
}

func (m *MockPlayerRepository) IncrementSkipCount(ctx context.Context, playerID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementSkipCount", ctx, playerID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (r *MockPlayerRepositoryMockRecorder) IncrementSkipCount(ctx, playerID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "IncrementSkipCount", reflect.TypeOf((*MockPlayerRepository)(nil).IncrementSkipCount), ctx, playerID)
}

func (m *MockPlayerRepository) Delete(ctx context.Context, playerID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, playerID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (r *MockPlayerRepositoryMockRecorder) Delete(ctx, playerID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "Delete", reflect.TypeOf((*MockPlayerRepository)(nil).Delete), ctx, playerID)
}
