// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ArtemHvozdov/bestieverse.git/internal/domain/repository (interfaces: SubtaskProgressRepository)

package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/ArtemHvozdov/bestieverse.git/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

type MockSubtaskProgressRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubtaskProgressRepositoryMockRecorder
}

type MockSubtaskProgressRepositoryMockRecorder struct {
	mock *MockSubtaskProgressRepository
}

func NewMockSubtaskProgressRepository(ctrl *gomock.Controller) *MockSubtaskProgressRepository {
	mock := &MockSubtaskProgressRepository{ctrl: ctrl}
	mock.recorder = &MockSubtaskProgressRepositoryMockRecorder{mock}
	return mock
}

func (m *MockSubtaskProgressRepository) EXPECT() *MockSubtaskProgressRepositoryMockRecorder {
	return m.recorder
}

func (m *MockSubtaskProgressRepository) Upsert(ctx context.Context, progress *entity.SubtaskProgress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, progress)
	ret0, _ := ret[0].(error)
	return ret0
}

func (r *MockSubtaskProgressRepositoryMockRecorder) Upsert(ctx, progress any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "Upsert", reflect.TypeOf((*MockSubtaskProgressRepository)(nil).Upsert), ctx, progress)
}

func (m *MockSubtaskProgressRepository) Get(ctx context.Context, gameID, playerID uint64, taskID string) (*entity.SubtaskProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, gameID, playerID, taskID)
	ret0, _ := ret[0].(*entity.SubtaskProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockSubtaskProgressRepositoryMockRecorder) Get(ctx, gameID, playerID, taskID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "Get", reflect.TypeOf((*MockSubtaskProgressRepository)(nil).Get), ctx, gameID, playerID, taskID)
}

func (m *MockSubtaskProgressRepository) Delete(ctx context.Context, gameID, playerID uint64, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, gameID, playerID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (r *MockSubtaskProgressRepositoryMockRecorder) Delete(ctx, gameID, playerID, taskID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "Delete", reflect.TypeOf((*MockSubtaskProgressRepository)(nil).Delete), ctx, gameID, playerID, taskID)
}
