// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ArtemHvozdov/bestieverse.git/internal/domain/repository (interfaces: GameRepository)

package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/ArtemHvozdov/bestieverse.git/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

type MockGameRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGameRepositoryMockRecorder
}

type MockGameRepositoryMockRecorder struct {
	mock *MockGameRepository
}

func NewMockGameRepository(ctrl *gomock.Controller) *MockGameRepository {
	mock := &MockGameRepository{ctrl: ctrl}
	mock.recorder = &MockGameRepositoryMockRecorder{mock}
	return mock
}

func (m *MockGameRepository) EXPECT() *MockGameRepositoryMockRecorder {
	return m.recorder
}

func (m *MockGameRepository) Create(ctx context.Context, game *entity.Game) (*entity.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, game)
	ret0, _ := ret[0].(*entity.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockGameRepositoryMockRecorder) Create(ctx, game any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "Create", reflect.TypeOf((*MockGameRepository)(nil).Create), ctx, game)
}

func (m *MockGameRepository) GetByChatID(ctx context.Context, chatID int64) (*entity.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByChatID", ctx, chatID)
	ret0, _ := ret[0].(*entity.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockGameRepositoryMockRecorder) GetByChatID(ctx, chatID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetByChatID", reflect.TypeOf((*MockGameRepository)(nil).GetByChatID), ctx, chatID)
}

func (m *MockGameRepository) GetByID(ctx context.Context, id uint64) (*entity.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockGameRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetByID", reflect.TypeOf((*MockGameRepository)(nil).GetByID), ctx, id)
}

func (m *MockGameRepository) GetByActivePollID(ctx context.Context, pollID string) (*entity.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByActivePollID", ctx, pollID)
	ret0, _ := ret[0].(*entity.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockGameRepositoryMockRecorder) GetByActivePollID(ctx, pollID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetByActivePollID", reflect.TypeOf((*MockGameRepository)(nil).GetByActivePollID), ctx, pollID)
}

func (m *MockGameRepository) UpdateStatus(ctx context.Context, id uint64, status entity.GameStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

func (r *MockGameRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "UpdateStatus", reflect.TypeOf((*MockGameRepository)(nil).UpdateStatus), ctx, id, status)
}

func (m *MockGameRepository) UpdateCurrentTask(ctx context.Context, id uint64, order int, publishedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCurrentTask", ctx, id, order, publishedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

func (r *MockGameRepositoryMockRecorder) UpdateCurrentTask(ctx, id, order, publishedAt any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "UpdateCurrentTask", reflect.TypeOf((*MockGameRepository)(nil).UpdateCurrentTask), ctx, id, order, publishedAt)
}

func (m *MockGameRepository) SetActivePollID(ctx context.Context, id uint64, pollID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActivePollID", ctx, id, pollID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (r *MockGameRepositoryMockRecorder) SetActivePollID(ctx, id, pollID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "SetActivePollID", reflect.TypeOf((*MockGameRepository)(nil).SetActivePollID), ctx, id, pollID)
}

func (m *MockGameRepository) GetAllActive(ctx context.Context) ([]*entity.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllActive", ctx)
	ret0, _ := ret[0].([]*entity.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockGameRepositoryMockRecorder) GetAllActive(ctx any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetAllActive", reflect.TypeOf((*MockGameRepository)(nil).GetAllActive), ctx)
}

func (m *MockGameRepository) SetFinished(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFinished", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

func (r *MockGameRepositoryMockRecorder) SetFinished(ctx, id any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "SetFinished", reflect.TypeOf((*MockGameRepository)(nil).SetFinished), ctx, id)
}
