// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ArtemHvozdov/bestieverse.git/internal/domain/repository (interfaces: NotificationRepository)

package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/ArtemHvozdov/bestieverse.git/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
}

type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

func (m *MockNotificationRepository) Create(ctx context.Context, log *entity.NotificationLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

func (r *MockNotificationRepositoryMockRecorder) Create(ctx, log any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "Create", reflect.TypeOf((*MockNotificationRepository)(nil).Create), ctx, log)
}

func (m *MockNotificationRepository) Exists(ctx context.Context, gameID, playerID uint64, taskID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, gameID, playerID, taskID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockNotificationRepositoryMockRecorder) Exists(ctx, gameID, playerID, taskID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "Exists", reflect.TypeOf((*MockNotificationRepository)(nil).Exists), ctx, gameID, playerID, taskID)
}

func (m *MockNotificationRepository) GetUnnotifiedPlayers(ctx context.Context, gameID uint64, taskID string) ([]*entity.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnnotifiedPlayers", ctx, gameID, taskID)
	ret0, _ := ret[0].([]*entity.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockNotificationRepositoryMockRecorder) GetUnnotifiedPlayers(ctx, gameID, taskID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetUnnotifiedPlayers", reflect.TypeOf((*MockNotificationRepository)(nil).GetUnnotifiedPlayers), ctx, gameID, taskID)
}
