// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ArtemHvozdov/bestieverse.git/internal/domain/repository (interfaces: PlayerStateRepository)

package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/ArtemHvozdov/bestieverse.git/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

type MockPlayerStateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerStateRepositoryMockRecorder
}

type MockPlayerStateRepositoryMockRecorder struct {
	mock *MockPlayerStateRepository
}

func NewMockPlayerStateRepository(ctrl *gomock.Controller) *MockPlayerStateRepository {
	mock := &MockPlayerStateRepository{ctrl: ctrl}
	mock.recorder = &MockPlayerStateRepositoryMockRecorder{mock}
	return mock
}

func (m *MockPlayerStateRepository) EXPECT() *MockPlayerStateRepositoryMockRecorder {
	return m.recorder
}

func (m *MockPlayerStateRepository) Upsert(ctx context.Context, state *entity.PlayerState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

func (r *MockPlayerStateRepositoryMockRecorder) Upsert(ctx, state any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "Upsert", reflect.TypeOf((*MockPlayerStateRepository)(nil).Upsert), ctx, state)
}

func (m *MockPlayerStateRepository) GetByPlayerAndGame(ctx context.Context, gameID, playerID uint64) (*entity.PlayerState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPlayerAndGame", ctx, gameID, playerID)
	ret0, _ := ret[0].(*entity.PlayerState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockPlayerStateRepositoryMockRecorder) GetByPlayerAndGame(ctx, gameID, playerID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetByPlayerAndGame", reflect.TypeOf((*MockPlayerStateRepository)(nil).GetByPlayerAndGame), ctx, gameID, playerID)
}

func (m *MockPlayerStateRepository) GetAllAwaitingByGame(ctx context.Context, gameID uint64) ([]*entity.PlayerState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAwaitingByGame", ctx, gameID)
	ret0, _ := ret[0].([]*entity.PlayerState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockPlayerStateRepositoryMockRecorder) GetAllAwaitingByGame(ctx, gameID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetAllAwaitingByGame", reflect.TypeOf((*MockPlayerStateRepository)(nil).GetAllAwaitingByGame), ctx, gameID)
}

func (m *MockPlayerStateRepository) SetIdle(ctx context.Context, gameID, playerID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIdle", ctx, gameID, playerID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (r *MockPlayerStateRepositoryMockRecorder) SetIdle(ctx, gameID, playerID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "SetIdle", reflect.TypeOf((*MockPlayerStateRepository)(nil).SetIdle), ctx, gameID, playerID)
}
