// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ArtemHvozdov/bestieverse.git/internal/domain/repository (interfaces: TaskLockRepository)

package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/ArtemHvozdov/bestieverse.git/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

type MockTaskLockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskLockRepositoryMockRecorder
}

type MockTaskLockRepositoryMockRecorder struct {
	mock *MockTaskLockRepository
}

func NewMockTaskLockRepository(ctrl *gomock.Controller) *MockTaskLockRepository {
	mock := &MockTaskLockRepository{ctrl: ctrl}
	mock.recorder = &MockTaskLockRepositoryMockRecorder{mock}
	return mock
}

func (m *MockTaskLockRepository) EXPECT() *MockTaskLockRepositoryMockRecorder {
	return m.recorder
}

func (m *MockTaskLockRepository) Acquire(ctx context.Context, gameID uint64, taskID string, playerID uint64, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx, gameID, taskID, playerID, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

func (r *MockTaskLockRepositoryMockRecorder) Acquire(ctx, gameID, taskID, playerID, expiresAt any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "Acquire", reflect.TypeOf((*MockTaskLockRepository)(nil).Acquire), ctx, gameID, taskID, playerID, expiresAt)
}

func (m *MockTaskLockRepository) Get(ctx context.Context, gameID uint64, taskID string) (*entity.TaskLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, gameID, taskID)
	ret0, _ := ret[0].(*entity.TaskLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockTaskLockRepositoryMockRecorder) Get(ctx, gameID, taskID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "Get", reflect.TypeOf((*MockTaskLockRepository)(nil).Get), ctx, gameID, taskID)
}

func (m *MockTaskLockRepository) Release(ctx context.Context, gameID uint64, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, gameID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (r *MockTaskLockRepositoryMockRecorder) Release(ctx, gameID, taskID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "Release", reflect.TypeOf((*MockTaskLockRepository)(nil).Release), ctx, gameID, taskID)
}

func (m *MockTaskLockRepository) ReleaseExpired(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseExpired", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

func (r *MockTaskLockRepositoryMockRecorder) ReleaseExpired(ctx any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "ReleaseExpired", reflect.TypeOf((*MockTaskLockRepository)(nil).ReleaseExpired), ctx)
}
