// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ArtemHvozdov/bestieverse.git/internal/domain/repository (interfaces: TaskResponseRepository)

package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/ArtemHvozdov/bestieverse.git/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

type MockTaskResponseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskResponseRepositoryMockRecorder
}

type MockTaskResponseRepositoryMockRecorder struct {
	mock *MockTaskResponseRepository
}

func NewMockTaskResponseRepository(ctrl *gomock.Controller) *MockTaskResponseRepository {
	mock := &MockTaskResponseRepository{ctrl: ctrl}
	mock.recorder = &MockTaskResponseRepositoryMockRecorder{mock}
	return mock
}

func (m *MockTaskResponseRepository) EXPECT() *MockTaskResponseRepositoryMockRecorder {
	return m.recorder
}

func (m *MockTaskResponseRepository) Create(ctx context.Context, response *entity.TaskResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, response)
	ret0, _ := ret[0].(error)
	return ret0
}

func (r *MockTaskResponseRepositoryMockRecorder) Create(ctx, response any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "Create", reflect.TypeOf((*MockTaskResponseRepository)(nil).Create), ctx, response)
}

func (m *MockTaskResponseRepository) GetByPlayerAndTask(ctx context.Context, gameID, playerID uint64, taskID string) (*entity.TaskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPlayerAndTask", ctx, gameID, playerID, taskID)
	ret0, _ := ret[0].(*entity.TaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockTaskResponseRepositoryMockRecorder) GetByPlayerAndTask(ctx, gameID, playerID, taskID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetByPlayerAndTask", reflect.TypeOf((*MockTaskResponseRepository)(nil).GetByPlayerAndTask), ctx, gameID, playerID, taskID)
}

func (m *MockTaskResponseRepository) GetAllByTask(ctx context.Context, gameID uint64, taskID string) ([]*entity.TaskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByTask", ctx, gameID, taskID)
	ret0, _ := ret[0].([]*entity.TaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockTaskResponseRepositoryMockRecorder) GetAllByTask(ctx, gameID, taskID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "GetAllByTask", reflect.TypeOf((*MockTaskResponseRepository)(nil).GetAllByTask), ctx, gameID, taskID)
}

func (m *MockTaskResponseRepository) CountAnsweredByTask(ctx context.Context, gameID uint64, taskID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAnsweredByTask", ctx, gameID, taskID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (r *MockTaskResponseRepositoryMockRecorder) CountAnsweredByTask(ctx, gameID, taskID any) *gomock.Call {
	r.mock.ctrl.T.Helper()
	return r.mock.ctrl.RecordCallWithMethodType(r.mock, "CountAnsweredByTask", reflect.TypeOf((*MockTaskResponseRepository)(nil).CountAnsweredByTask), ctx, gameID, taskID)
}
