id: "task_07"
order: 7
type: question_answer
media_file: "tasks/task_07.gif"

text: |
  🚨 <b>УВІМКНЕНО РЕЖИМ НИТІНГ!</b>

  Увага, увага! Оголошується офіційне відкриття <b>«Клубу тих, кого бісить усе»</b> 🧨

  <b>Що тебе зараз реально виводить із себе?</b>

  🤧 Соплі дітей по колу?
  🐶 Сусідський пес і його 💩 на газоні?
  🌧️ Волосся у режимі «кульбабка» в дощ?
  🍫 Ціни на «Рафаелло», встановлені темною магією?
  😵‍💫 Або щось ну зовсім дрібне, але дуууже бісяче?

  📌 Формат – аудіо або відеокружечок.
  З емоціями, перебільшенням та драмою.

  Починаємо просто:
  <b>«МЕНЕ БІСИТЬ, ЩО...»</b>
  А далі – не стримуйся!

  Бо знаєш що?
  <b>Нити – це теж терапія.</b>
  Більше того: ми досі здатні з цього гарно посміятися 😄

summary:
  type: text
  text: |
    О-о-о, я відчуваю цю енергію бунту, з нею можна перевернути будь-які гори!

    І що б там не було – ти витримаєш, переможеш і зробиш це розкішно, Королево!💃


