id: "task_11"
order: 11
type: question_answer
media_file: "tasks/task_11.gif"

text: |
  🎥 <b>РЕПОРТАЖ СОФІ ЛАПЕН</b>


  – Bonjour! На зв’язку журналістка Софі Лапен. Разом із французькими вченими я вже третій рік досліджую <b>магію жіночої дружби</b>.

  Після вашої шаленої самовіддачі у <b>Bestieverse</b> я просто не можу лишитися осторонь 😄

  Запрошую тебе стати героїнею документального фільму <b>«Між нами дівчатами»</b> і поділитися своєю філософією про дружбу 💫

  📌 <b>Запиши відео-інтерв’ю, відповівши на кілька запитань:</b>

  1️⃣ У яких дрібницях проявляється справжня магія вашої дружби?
  2️⃣ Опиши ваш ідеальний день з Бесті.
  3️⃣ Якби ти могла додати одну річ у світ, щоб життя кожної подруги стало кращим, що б це було?
  4️⃣ Чого, на твою думку, світ досі не розуміє про жіночу дружбу?
  5️⃣ Коли ти відчула найбільшу підтримку й цінність вашої дружби саме під час цієї гри?

  🎞 Мотор, Камера, Зйомка, Хочу відповісти, Надіслати.

  P.S. Це <b>передостаннє завдання</b> гри – шанс підсумувати ваші пригоди й залишити теплий слід у Bestieverse 💛

summary:
  type: text
  text: |
    Дякую, леді. Я все опрацювала та впевнена: ваші відповіді допоможуть зробити прорив у нашому дослідженні і ми нарешті знайдемо відповідь на запитання:

    Чому якась подруга приходить у твоє життя, але не затримується, а якась безцеремонно: «Посунься, сіста, я з тобою тут надооооовго…» 

    <i>Bisous-bisous, Sophie Lapin</i> ❤️