id: "task_01"
order: 1
type: question_answer
media_file: "tasks/task_01.gif"

text: |
  🥨 <b>ЗАМІШУЄМО ТІСТО</b>

  Я хочу, щоб ця пригода перетворила <b>відстань на новий формат близькості</b>. І вона починається прямо зараз ✨

  Для розігріву пропоную пригадати, як замішувалося тісто для вашої булочки 🥐

  Пам’ятаєш той магічний момент, <b>коли ви вперше побачили одна одну</b>?

  Можливо, хтось позичав зошит на 12 аркушів у «третьому Б» або випадково облив іншу просеко у «Форсажі»? 🍾

  📌 Запиши <b>відеокружечок</b>, <b>аудіоспогад</b> або просто напиши <b>текстом</b>: з чого саме почалася ця велика дружба, що зібрала вас тут.

  Тисни <b>“Хочу відповісти”</b> і погнали!
  Одна подруга – одна історія ✨

summary:
  type: predictions
  header_text: |
    Воу-воу, дівчата, гра починає набирати оберти! Далі ще цікавіше! Очікуйте наступне завдання вже через годину.

    А поки що не сумуйте і ловіть рандомні передбачення на наступний тиждень.

  predictions:
    - "🔮 {{.Mention}} зорі кажуть, що ти – єдиноріг у світі поні! Але не дивуйся, якщо знайдеш під подушкою броколі… Це Всесвіт натякає: пора спробувати щось нове!"
    - "🔮 {{.Mention}} сьогодні твоя аура випромінює флюїди космічного блаженства. Головне – не сперечайся з голубами. Вони знають більше, аніж кажуть."
    - "🔮 {{.Mention}} готується потік удачі! Але спочатку він може з’явитися у вигляді заплутаних навушників або какао, яке охолоне саме тоді, коли ти вирішиш його випити."
    - "🔮 {{.Mention}} любовний гороскоп: ти магніт для дивних збігів. Очікуй, що твоє серденько затріпоче, коли хтось випадково поряд з тобою впустить бутерброд."
    - "🔮 {{.Mention}} наступного тижня на тебе чекає велике відкриття. Можливо, це відкриється талант до танців із чайною ложечкою. Або нова пачка улюбленого печива."