id: "task_05"
order: 5
type: question_answer
media_file: "tasks/task_05.gif"

text: |
  💬 Оʼкей, а тепер – <b>ЯК ТИ?</b>

  Ми вже пригадали, з чого все почалося. А тепер – маленька <b>зупинка в теперішньому</b>.

  Поділися, як ти живеш зараз і як тобі у цьому моменті. Не для інспекції – щоб <b>відчути одна одну</b> 👩🏼‍❤️‍👩🏻

  <b>Продовжи фрази</b>:
  💡 «Останнім часом мене надихає...»
  🛁 «Ритуал, який додає мені енергії...»
  🫠 «Нещодавно мене особливо потішило...»
  👏 «Маленька річ, якою я сьогодні задоволена...»
  💛 «Мені хочеться подякувати собі за...»

  📌 Пиши, надиктовуй, знімай – як відчувається.
  Орфографія – опціонально 😜

summary:
  type: text
  text: "Дружба – це підтримка, сміх до сліз та історії, які ніхто інший не зрозуміє 😌 Не забувай: у тебе є людина, яка завжди близько, навіть якщо зараз далеко 💛"