id: "task_10"
order: 10
type: poll_then_task
media_file: "tasks/task_10.gif"

text: |
  🎤 <b>Оголошується КОНКУРС ТАЛАНТІВ!</b>

  Так-так, настав момент, коли треба показати свої приховані таланти 💥
  Не впевнені, що вони у вас є? Не біда – зараз знайдемо! 🕵️‍♀️✨

  📌 <b>Що робити?</b>

  0️⃣ Нижче я надішлю три смішні завдання на вибір
  1️⃣ Голосуєш за завдання, яке тобі найбільше до душі
  2️⃣ Чекаєш, поки проголосують інші
  3️⃣ Перемагає завдання, яке набрало найбільше лайків. Нічия? Перемагає те, за яке віддали перший голос.


pol:
  title: "Голосування відкрито:"

  options:
    - id: "dance"
      label: "🙈 Несамовито станцювати “Abracadabra” Леді Гаги"
      result_type: question_answer
      prepared_text: |
        Ваше завдання... 🥁

        <b>Станцювати “Abracadabra” Леді Гаги</b>

        Гьорлз, ось цей <a href="https://www.youtube.com/shorts/Cb5ljmm3820?si=qWu3oIgz890cV0xo">ентузіаст</a> вас точно замотивує до палкого танцю; і не забудьте про розминку! 

        📌 <b>Умови конкурсу:</b>

        1️⃣ Виконати завдання так, ніби це відбір до “Україна має талант”. Місце – на ваш вибір. Тривалість – скільки душа забажає.
        2️⃣ Зняти свій виступ на відео. (Це обов’язково, бо інакше ніхто не повірить!)
        3️⃣ Відправити відео у групу через кнопку “Хочу відповісти”.
        4️⃣ За бажанням запостити в Інста з хештегом #Bestieverse та згадкою <a href="https://www.instagram.com/yourbestieverse/">нашої сторінки</a>.

        P.S. Саме слово “Abracadabra” традиційно означає магічне заклинання, і Леді Гага 🎩 використовує його як символ чарівності та перевтілення на сцені.

        Я у вас вірю! Цьом 💋

    - id: "sing"
      label: "🙉 Заспівати шлягер Фібі Буфе “Smelly Cat”"
      result_type: question_answer
      prepared_text: |
        Ваше завдання… 🥁

        <b>Заспівати шлягер Фібі Буфе “Smelly Cat”</b>

        5 сирих яєць для тоненького голосочку, каструля з ложками для ритму і <b>той самий текст пісні</b> 🥹:

        <i>Smelly Cat, Smelly Cat,</i>
        <i>What are they feeding you?</i>
        <i>Smelly Cat, Smelly Cat</i>
        <i>It's not your fault</i>
        <i>They won't take you to the vet</i>
        <i>You're obviously not their favorite pet</i>
        <i>Smelly Cat, Smelly Cat,</i>
        <i>It's not your fault</i>

        Потренуйтеся попадати в ноти з “Друзями” <a href="https://www.youtube.com/watch?v=Mkuw7vdi-VA">тут</a>. 

        📌 <b>Умови конкурсу:</b>

        1️⃣ Виконати завдання так, ніби це відбір до “Україна має талант”.
        2️⃣ Зняти виступ на відео. (Це обов’язково, бо інакше ніхто не повірить!)
        3️⃣ Відправити відео у групу через кнопку “Хочу відповісти”.
        4️⃣ За бажанням запостити в Інста з хештегом #Bestieverse та згадкою <a href="https://www.instagram.com/yourbestieverse/">нашої сторінки</a>.

        P.S. Назва “Smelly Cat” – буквально «Смердючий Кіт» – придумана як абсурдний і кумедний протест проти незручностей життя: Фібі співала про кота, якого ніхто не любить, але який заслуговує на любов 😽

        Я у вас вірю! Цьом 💋

    - id: "memes"
      label: "🙊 Озвучити потік мемасиків і вкотре довести геніальність українського дубляжу"
      result_type: meme_voiceover
      meme_files:
        - "task_10/meme_01.gif"
        - "task_10/meme_02.gif"
        - "task_10/meme_03.gif"
        - "task_10/meme_04.gif"
        - "task_10/meme_05.gif"
        - "task_10/meme_06.gif"
        - "task_10/meme_07.gif"
        - "task_10/meme_08.gif"
        - "task_10/meme_09.gif"
        - "task_10/meme_10.gif"
        - "task_10/meme_11.gif"
        - "task_10/meme_12.gif"
        - "task_10/meme_13.gif"
        - "task_10/meme_14.gif"
        - "task_10/meme_15.gif"
        - "task_10/meme_16.gif"
        - "task_10/meme_17.gif"
        - "task_10/meme_18.gif"
        - "task_10/meme_19.gif"
        - "task_10/meme_20.gif"
        - "task_10/meme_21.gif"
        - "task_10/meme_22.gif"
        - "task_10/meme_23.gif"
        - "task_10/meme_24.gif"
        - "task_10/meme_25.gif"  

summary:
  type: text
  text: |
    Зіроньки, тепер ви – <b>реальні зірки!</b> ✨

    Не забувайте про хештег #Bestieverse якщо захочете прославитися в <a href="https://www.instagram.com/yourbestieverse/">Інстаграмах</a>
