id: "task_08"
order: 8
type: question_answer
media_file: "tasks/task_08.gif"

text: |
  🫂 <b>ОБІЙМИ СЕБЕ!</b>

  Ну що, виговорилася? Випустила пару?
  Після хорошого нитінгу обовʼязково треба закріпити ефект розвантаження – <b>обійняти себе</b>.

  Серйозно, крихітко:
  сьогодні треба обійняти себе
  <b>Діями</b>
  І для цього від мене нове завдання ✨

  📌 Протягом наступних 24 годин зроби щось приємне саме для себе.
  Не корисне. Не правильне.
  А те, від чого тобі реально добре.

  <b>Ось кілька ідей для натхнення:</b>

  🎥 Скасувати зум і піти на каву «з собою»
  😂 Зашторитися і безсоромно подивитися весь “Stranger Things” одним махом
  🛀 Ванна, маска, келих і улюблена група з колонок

  P.S. Чому це завдання у грі про дружбу?
  Бо справжня бесті завжди порадіє, коли тобі класно 💌

  А тепер – уперед!
  І обовʼязково <b>поділися у групі хоча б одним кадром</b> того твого «мені кайфово» 📸

summary:
  type: text
  text: |
    О, круасанчики, це було прекрасно! Чому не робити чогось такого кожного дня? Ви тільки уявіть, наскільки просвітленими ви можете стати! 🧘🏻‍♀️

    У поміч я підготувала список <b>ресурсних занять</b>. Завантажуйте, роздруковуйте, доповнюйте власними ритуалами, які тішать і наповнюють.

    Рухайтеся від одного пункту до іншого на регулярній основі! 

    Обіймаю 🧡
