id: "task_04"
order: 4
type: question_answer
media_file: "tasks/task_04.gif"

text: |
  🎭 <b>ХТО З НАС?</b>

  Бешкетниці, настав час <b>тестувати вашу дружбу</b>!

  Тут буде весело, тут буде чесно і тут можуть відкритися страшні секрети 👻

  Але домовимось одразу: усе з любов’ю 💛 Тому голосуємо, сміємося і не ображаємося!

  📌 Натискай «Відповісти» і <b>обирай ту, котра з вас...</b>
  Думай швидко. Відповідай інтуїтивно.

questions:
  - id: "q1"
    text: "🍕 Хто з нас з’їсть останній шматок піци і вдаватиме, що він там ніколи не лежав?"
  - id: "q2"
    text: "🤯 Хто з нас забуде, навіщо зайшов у кімнату, і піде назад?"
  - id: "q3"
    text: "💤 Хто з нас може проспати навіть власний день народження?"
  - id: "q4"
    text: "🦹‍♀️ Хто з нас вижив би у зомбі-апокаліпсисі?"
  - id: "q5"
    text: "🧟‍♀️ А хто би став зомбі першого ж дня?"
  - id: "q6"
    text: "🤐 Хто з нас найшвидше розкаже секрет, навіть якщо перед тим клялася мовчати?"
  - id: "q7"
    text: "🤡 Хто з нас може розсміятися в найнедоречніший момент?"
  - id: "q8"
    text: "♏️ Хто з нас найбільше вірить у гороскопи? (І знає знаки зодіаку всіх наших колишніх?)"
  - id: "q9"
    text: "🎞 Хто з нас може сказати  “ну, іще одна серія...” і дивитися до четвертої ранку?"
  - id: "q10"
    text: "🦠 Хто з нас стане вірусним мемом після корпоративу?"

summary:
  type: who_is_who_results
  header_text: |
    Круасанчики, ролі у вашому серіалі визначено 🍿
    Усе збігається? 😏

