id: "task_06"
order: 6
type: question_answer
media_file: "tasks/task_06.gif"

text: |
  📸 <b>ДЕНЬ ІЗ ЖИТТЯ БОГИНІ</b>

  [іншими словами... 
  ...твій звичайний день]

  Ви точно в курсі про усі <b>великі події</b> у житті подруг – весілля, карʼєрні злети або той священний момент, коли гора прання нарешті кудись зникає.

  Але наскільки добре ви знаєте, з чого складається <b>звичайний день</b> кожної з вас – з 08:00 до 23:59? 👀

  Чим бесті снідає, скільки часу укладає зачіску і чи симпатичний бариста біля її офісу?

  📌 <b>Отже, що робити</b>:

  1️⃣ <b>Зніми або сфотографуй ключові моменти свого дня</b>: філіжанка ранкової кави, робочі задачі, прокрастинація після обіду та вечірній чіл 🍩

  2️⃣ <b>Надішли у групу 6 фото / відео</b> (це програма мінімум: чим більше - тим краще)

  <b>Але!</b> Одне з них має бути фейк – вигадка, містифікація, фальшивка 🤡

  3️⃣ <b>Подруги мають вгадати, де ти схитрувала</b>
  Та, хто першою знайде “фантазію”, стає Королевою Інтуїції 👑

  Чекаємо твого звіту 📸🕵‍♀️✨

summary:
  type: text
  text: |
    Це було потужно!

    Поки що відпочивайте, а я обіцяю: наступне завдання буде легшим, але це не точно 😁